#!/usr/bin/env perl

use strict;
use warnings;

my @names = qw(
    black
    red
    green
    yellow
    blue
    magenta
    cyan
    white
);

printf("%-10s", $_) for qw( Regular Bold Reverse Blink Crossed Italic Underline );
print "\n" . "-"x78 . "\n";

foreach my $col (0..7) {
    my $fcol = 30 + $col;
    my $name = sprintf("%-10s", $names[$col]);
    print
        "\x1b[0m", "\x1b[${fcol}m",   $name,
        "\x1b[0m", "\x1b[${fcol};1m", $name,
        "\x1b[0m", "\x1b[${fcol};7m", $name,
        "\x1b[0m", "\x1b[${fcol};5m", $name,
        "\x1b[0m", "\x1b[${fcol};9m", $name,
        "\x1b[0m", "\x1b[${fcol};3m", $name,
        "\x1b[0m", "\x1b[${fcol};4m", $name,
        "\x1b[0m", "\n"
    ;
}
