#!/usr/bin/env perl

use strict;
use warnings;

use Term::ReadKey;
my ($cols) = GetTerminalSize();

my $timestamp = scalar(localtime());

my $lines = 1;
my $marker = '-';

while (@ARGV) {
    my $arg = shift @ARGV;

    if ($arg =~ m{^\d+$}o) {
        $lines = $arg;
    } else {
        $marker = $arg;
    }
}

my $r_width = int(($cols - length($timestamp) - 2) / 2);
my $l_width = $cols - length($timestamp) - $r_width - 2;

printf("%s %s %s\n", rep($marker, $l_width), $timestamp, rep($marker, $r_width))
    for 1..$lines;

sub rep {
    my ($rep, $len) = @_;

    return unless defined $rep && defined $len;
    return unless $len > 0 && length($rep) > 0;

    return substr(($rep x ($len / length($rep))) . $rep, 0, $len);
}
